name = "IamExplainer"
version = "0.1.0"
defaultTargets = ["iamlean"]

[[lean_lib]]
name = "Seclib"

[[lean_lib]]
name = "IamExplainer"

[[lean_lib]]
name = "IAMRules"

[[lean_exe]]
name = "iamlean"
root = "Main"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "v4.33.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "master"
scope = "dev"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.33.1"
scope = "dev"
